/* Autogenerated by hxtools bin2c */
#ifndef LT7911_FW_H
#define LT7911_FW_H 1

#ifdef __cplusplus
extern "C" {
#endif

#define version 0x0B
#define LT7911_DEMO_FW_LENGTH 47820
extern const unsigned char LT7911_FW[LT7911_DEMO_FW_LENGTH];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* LT7911_FW_H */
